### ISSUE TITLE
Package 'estudy2' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Finance#3]
Package [estudy2](https://CRAN.R-project.org/package=estudy2) is currently listed in CRAN Task View [Finance](https://CRAN.R-project.org/view=Finance) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by eddelbuettel** [comment]
Fixed twelve days ago in this commit: https://github.com/cran-task-views/Finance/commit/872a723e5b2bffeeaead0e5284a5b2a85c7836ce

Please check for repository status before unleashing bug reports in a loop.
