### ISSUE TITLE
Soon to be released packages

### ISSUE THREAD

**Issue by serkor1** [cran-task-views/Finance#9]
Hi @eddelbuettel 

What is the policy of soon-to-be published packages?
- Can these be added before CRAN accepts the package?

Best,

**Comment by eddelbuettel** [comment]
In principle, yes.  Task Views also have sections for non-CRAN packages on GitHub.  But that is rare and the exception.  Note the 'CRAN' in 'CRAN Task Views'.  So in practice it is rare and needs good motivation.

Can you share what you had in mind?

**Comment by serkor1** [comment]
Well, I am working on this [package](https://github.com/kochiuyu/CandleStickPattern).

I haven't seen a similar package in R so far, and I believe it will be useful for the Finance ecosystem.

We are planning a submission in early march - and were hoping we could have it listed on Task View upon release. 

Best,

**Comment by eddelbuettel** [comment]
Maybe write a blog post about it?  CRAN Task View is not the only way to promote a package.
